### ISSUE TITLE
getRecord($host, DNS_CNAME) does not work

### ISSUE THREAD

**Issue by fordnox** [hostinger/php-dig#5]
This class needs to be tested.

It does not return correct values when simple `dns_get_record($host, DNS_CNAME);` does return correct values.

for testing you can use this one:
https://toolbox.googleapps.com/apps/dig/#CNAME/www.example-free.tk

or the implementation on 000webhost is wrong

**Comment by vaidas-lungis** [comment]
checked with 
`php artisan tinker`

```php
>>> app(Hostinger\DigClient::class)->getRecord('www.example-free.tk', DNS_CNAME);
=> [
     [
       "host" => "www.example-free.tk",
       "ttl" => "14439",
       "class" => "IN",
       "type" => "CNAME",
       "target" => "putna.000webhostapp.com.",
     ],
   ]
```

Provide more information ? Could not logged in into 000 panel at the moment..

**Comment by vaidas-lungis** [comment]
Sometimes `dig` return empty result when dns_get_record() returns items..

**Comment by vaidas-lungis** [comment]
@fordnox 
After logging both dig and dns_get_record responses on same request  did not see any critical issues. Sometimes dig response is empty, sometimes dns_get_record(), sometimes they return different target values (maybe different dns returns different values?)

Suggestion for 000webhost: 
revert back to dig: better performance, no errors `dns_get_record(): A temporary server error occurred`
 And add logs on negative response to analyse situation
